// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAId-_PhSWbb9oOaxRuZJqyIIvzSIRQ50c',
    appId: '1:58488867615:web:252a9b67264809f6677e2a',
    messagingSenderId: '58488867615',
    projectId: 'samatoll-85d16',
    authDomain: 'samatoll-85d16.firebaseapp.com',
    storageBucket: 'samatoll-85d16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMYoyk8YjVANi5n4vT8dh8uksJ4g-kY1A',
    appId: '1:58488867615:android:e8da91c3252eea10677e2a',
    messagingSenderId: '58488867615',
    projectId: 'samatoll-85d16',
    storageBucket: 'samatoll-85d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQeixvuVVV5nELNFpeaJ3YNagR1IUa7QQ',
    appId: '1:58488867615:ios:291def9e47f8cd46677e2a',
    messagingSenderId: '58488867615',
    projectId: 'samatoll-85d16',
    storageBucket: 'samatoll-85d16.firebasestorage.app',
    iosBundleId: 'com.example.samatoll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQeixvuVVV5nELNFpeaJ3YNagR1IUa7QQ',
    appId: '1:58488867615:ios:291def9e47f8cd46677e2a',
    messagingSenderId: '58488867615',
    projectId: 'samatoll-85d16',
    storageBucket: 'samatoll-85d16.firebasestorage.app',
    iosBundleId: 'com.example.samatoll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAId-_PhSWbb9oOaxRuZJqyIIvzSIRQ50c',
    appId: '1:58488867615:web:3833c76add97e080677e2a',
    messagingSenderId: '58488867615',
    projectId: 'samatoll-85d16',
    authDomain: 'samatoll-85d16.firebaseapp.com',
    storageBucket: 'samatoll-85d16.firebasestorage.app',
  );
}
